# ç­–ç•¥ç»„ (Proxy Groups)
proxy-groups:
  - name: "å‰ç½®èŠ‚ç‚¹"
    type: select
    include-all: true
    filter: "ğŸš€" # ä¿ç•™
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png"

  - name: "è½åœ°èŠ‚ç‚¹"
    type: select
    include-all: true
    filter: "ğŸ " # ä¿ç•™
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/China.png"

  - name: "ä¸­è½¬èŠ‚ç‚¹"
    type: select
    include-all: true
    filter: "ğŸ¯" # ä¿ç•™
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Personal.png"

  - name: "æœºåœºèŠ‚ç‚¹"
    type: select
    include-all: true
    filter: "âœˆï¸" # ä¿ç•™
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png"

  - name: "å…¨çƒåŠ é€Ÿ"
    type: select
    proxies: [ "å‰ç½®èŠ‚ç‚¹","è½åœ°èŠ‚ç‚¹","ä¸­è½¬èŠ‚ç‚¹", "æœºåœºèŠ‚ç‚¹", "DIRECT"]
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png"

  - name: "æµ·å¤–æœåŠ¡"
    type: select
    include-all: true
    filter: "ğŸ¯" # ä¿ç•™
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png"

  - name: "AdBlock"
    type: select
    proxies: [REJECT]
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Adblock.png" 
  
  - name: "å…œåº•åˆ†æµ"
    type: select
    proxies: [ "å‰ç½®èŠ‚ç‚¹","è½åœ°èŠ‚ç‚¹","ä¸­è½¬èŠ‚ç‚¹", "æœºåœºèŠ‚ç‚¹", "DIRECT"]
    icon: "https://ghfast.top/https://raw.githubusercontent.com/Orz-3/mini/master/Color/Final.png"


# è§„åˆ™æä¾›è€… (Rule Providers)
rule-providers:
  # å¹¿å‘Šè§„åˆ™
  ads: { behavior: domain, interval: 86400, path: ./provider/rule-set/ads.mrs, format: mrs, type: http, url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-all.mrs" }

  # GFW åˆ—è¡¨
  gfw: { behavior: domain, interval: 86400, path: ./provider/rule-set/gfw.mrs, format: mrs, type: http, url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/gfw.mrs" }
  
  # éä¸­å›½åŒºåŸŸå
  geolocation-!cn: { behavior: domain, interval: 86400, path: ./provider/rule-set/geolocation-!cn.mrs, format: mrs, type: http, url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/geolocation-!cn.mrs" }
  
  # ä¸­å›½åŒºIPåœ°å€
  cn-ip: { behavior: ipcidr, interval: 86400, path: ./provider/rule-set/cn_ip.mrs, format: mrs, type: http, url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/cn.mrs" }

  # private:
  private: { behavior: ipcidr, interval: 86400, path: ./provider/rule-set/private.mrs, format: mrs, type: http, url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/private.mrs" }
  
  # ä¸­å›½åŒºåŸŸå
  cn-domain: { behavior: domain, interval: 86400, path: ./provider/rule-set/cn_domain.mrs, format: mrs, type: http, url: "https://ghfast.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/cn.mrs" }
  
  # fake-ip è¿‡æ»¤å™¨
  fake-ip-filter: { behavior: domain, format: text, interval: 86400, path: ./provider/rule-set/fake_ip_filter.list, type: http, url: "https://cdn.jsdelivr.net/gh/juewuy/ShellCrash@dev/public/fake_ip_filter.list", }
  
  # è‡ªå®šä¹‰è§„åˆ™
  custom-direct: { behavior: classical, interval: 86400, path: ./provider/rule-set/custom_direct.yaml, type: http, format: yaml, url: "https://ghfast.top/https://raw.githubusercontent.com/mufeng688/Sub-Config/refs/heads/main/rule/DiyDirect.yaml" }
  custom-proxy: { behavior: classical, interval: 86400, path: ./provider/rule-set/custom_proxy.yaml, type: http, format: yaml, url: "https://ghfast.top/https://raw.githubusercontent.com/mufeng688/Sub-Config/refs/heads/main/rule/DiyProxy.yaml" }

# è§„åˆ™ (Rules)
rules:
  # å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,ads,AdBlock
  
  # å±€åŸŸç½‘ä¸ç§æœ‰åœ°å€ç›´è¿
  - RULE-SET,private,DIRECT # æ­¤æ¡ä¸ºå†…ç½®è§„åˆ™ï¼Œæ— éœ€æ•°æ®åº“ï¼Œå»ºè®®ä¿ç•™

  # è‡ªå®šä¹‰è§„åˆ™ä¼˜å…ˆ
  - RULE-SET,custom-proxy,æµ·å¤–æœåŠ¡
  - RULE-SET,custom-direct,DIRECT

  # å›½å†…æœåŠ¡ç›´è¿
  - RULE-SET,cn-domain,DIRECT
  - RULE-SET,cn-ip,DIRECT

  # éœ€è¦ä»£ç†çš„æµé‡
  - RULE-SET,gfw,å…¨çƒåŠ é€Ÿ
  - RULE-SET,geolocation-!cn,å…¨çƒåŠ é€Ÿ

  # å…œåº•è§„åˆ™ï¼Œæ‰€æœ‰æœªåŒ¹é…çš„æµé‡éƒ½èµ°è¿™é‡Œ
  - MATCH,å…œåº•åˆ†æµ
